Embedded MongoDB Configuration ------------------------------
	If the current code compiles, the application will likely not start as it can't find a Mongo database.

	[INFO] Loading Bootstrap Data...
	[DEBUG] Created query Query: { "name" : "Cup"}, Fields: {}, Sort: {}
	[DEBUG] find using query: { "name" : "Cup"} fields: Document{{}} for class: class guru.springframework.spring5recipeapp.domain.UnitOfMeasure in collection: unitOfMeasure
	[INFO] Cluster description not yet available. Waiting for 30000 ms before timing out
	[DEBUG] Closing connection connectionId{localValue:1}
	[INFO] Exception in monitor thread while connecting to server localhost:27017
	com.mongodb.MongoSocketOpenException: Exception opening socket
		at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:70)
		at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:127)
		at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.net.ConnectException: Connection refused: connect
		at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
		at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:81)
		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
		at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:162)
		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
		at java.net.Socket.connect(Socket.java:606)
		at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:63)
		at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:79)
		at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65)
		... 3 common frames omitted
	[DEBUG] Updating cluster description to  {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]
	[DEBUG] Closing connection connectionId{localValue:2}

	...

	Caused by: java.lang.ClassNotFoundException: org.springframework.jdbc.CannotGetJdbcConnectionException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 15 common frames omitted
	[ERROR] Application run failed
	org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: connect}}]

	Luckily we can setup an embedded MongoDB

	* Add dependencies

			<dependency>
				<groupId>de.flapdoodle.embed</groupId>
				<artifactId>de.flapdoodle.embed.mongo</artifactId>
			</dependency>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-data-mongodb</artifactId>
			</dependency>

	* application.properties
		spring.data.mongodb.port=0					# This makes MongoDB run on any (ramdom) port => [INFO] Opened connection [connectionId{localValue:1, serverValue:1}] to localhost:50553
		spring.data.mongodb.host=localhost

	RESULT: ERROR due to lack of proper entity and relationship setup as we removed all the JPA annotations?

	[ERROR] Application run failed
		guru.springframework.spring5recipeapp.exception.ObjectNotFoundException: UOM Cup not found!
			at guru.springframework.spring5recipeapp.service.UnitOfMeasureRepositoryServiceImpl.lambda$getUOMByName$0(UnitOfMeasureRepositoryServiceImpl.java:32)
			at java.util.Optional.orElseThrow(Optional.java:290)
			at guru.springframework.spring5recipeapp.service.UnitOfMeasureRepositoryServiceImpl.getUOMByName(UnitOfMeasureRepositoryServiceImpl.java:32)
			at guru.springframework.spring5recipeapp.bootstrap.H2DataInitializer.getUnitOfMeasureByName(H2DataInitializer.java:200)
			at guru.springframework.spring5recipeapp.bootstrap.H2DataInitializer.getRecipes(H2DataInitializer.java:63)
			at guru.springframework.spring5recipeapp.bootstrap.H2DataInitializer.onApplicationEvent(H2DataInitializer.java:57)

		Basically what is happening here is the the Bootstrap class is crashing because the SQL inserts are now no longer being executed which insert the UOMs and categories into the database at startup!
		So we will have to add code for this to the bootstrap class which will execute BEFORE the existing code which tries to insert example recipe data!

Refactoring Data Model for MongoDB
----------------------------------

	MongoDB doesn't have traditional relationship mappings like in RDBMS
		=> 3 Documents: UOM, Category, Recipe (with all related stuff inside, and we still want to use our UOMs here as well)
		So these 3 class we annotate with @Document (org.springframework.data.mongodb.core.mapping.Document) and any references to the other Document classes we annotate with @DBRef
		All id properties are still annotated with Spring Data @Id

	@Data
	@Document
	public class UnitOfMeasure {

		@Id
		private String id;
		private String name;
		private String unit;
	}

	@Getter
	@Setter
	public class Ingredient {

		@Id
		private String id;
		private BigDecimal amount;
		private String name;

		@DBRef										// In the ingredient add a database reference to the unit of measure Document!
		private UnitOfMeasure unitOfMeasure;
		//private Recipe recipe;					// Commented out this bidirectional reference
		...
	}

	@Data
	@EqualsAndHashCode(exclude = {"categories", "notes"})
	// Excluded categories and notes, but left in recipes for equals and hashCode generation as it seems an essential
	// part of the recipe
	@Document
	public class Recipe {

		@Id
		private String id;
		private String cookInstructions;
		private String description;
		private Integer cookTimeMins;
		private Difficulty difficulty;
		private Byte[] image;
		private String name;
		private Integer prepTimeMins;
		private String source;
		private String url;
		private String yield;

		@DBRef
		private Set<Category> categories = new HashSet<>();
		private Set<Ingredient> ingredients = new HashSet<>();
		private Notes notes;
		...

		public Recipe addIngredient(Ingredient ingredient) {
			this.ingredients.add(ingredient);
			//ingredient.setRecipe(this);                   // Commented out this bidirectional reference

			return this;
		}

		public Recipe addIngredients(Set<Ingredient> ingredients) {
			//ingredients.stream().forEach(ingredient -> ingredient.setRecipe(this));       // Commented out this bidirectional reference
			this.setIngredients(ingredients);

			return this;
		}

		public Recipe addNotes(Notes notes) {
			this.setNotes(notes);
			//notes.setRecipe(this);                        // Commented out this bidirectional reference

			return this;
		}
	}

	@Data
	@EqualsAndHashCode(exclude = "recipes")
	@Document
	public class Category {

		@Id
		private String id;
		private String name;

		@DBRef
		private Set<Recipe> recipes = new HashSet<>();
		...
	}

	Refactoring the bootstrap class to fix the startup issue (inserting categories and UOMs into the database prior to trying to insert recipes`):

		package guru.springframework.spring5recipeapp.bootstrap;

		...

		// Use this for adding example data to a test database
		@Component
		@Slf4j
		@Profile("default")
		public class DataInitializer implements ApplicationListener<ContextRefreshedEvent> {

			private final CategoryRepository categoryRepository;
			private final RecipeRepository recipeRepository;
			private final UnitOfMeasureRepository unitOfMeasureRepository;
			private final CategoryService categoryService;
			private final UnitOfMeasureService unitOfMeasureService;

			@Autowired
			public DataInitializer(CategoryRepository categoryRepository,
								   RecipeRepository recipeRepository,
								   UnitOfMeasureRepository unitOfMeasureRepository,
								   CategoryService categoryService,
								   UnitOfMeasureService unitOfMeasureService) {
				this.categoryRepository = categoryRepository;
				this.recipeRepository = recipeRepository;
				this.unitOfMeasureRepository = unitOfMeasureRepository;
				this.categoryService = categoryService;
				this.unitOfMeasureService = unitOfMeasureService;
			}

			@Override
			@Transactional
			public void onApplicationEvent(ContextRefreshedEvent contextRefreshedEvent) {
				log.info("Loading Bootstrap Data...");
				loadCategories();
				loadUom();
				recipeRepository.saveAll(getRecipes());
			}

			private void loadCategories(){
				Category cat1 = new Category();
				cat1.setName("American");
				categoryRepository.save(cat1);

				Category cat2 = new Category();
				cat2.setName("Fast Food");
				categoryRepository.save(cat2);

				Category cat3 = new Category();
				cat3.setName("Good Belgian Cooking");
				categoryRepository.save(cat3);

				Category cat4 = new Category();
				cat4.setName("Fast Italian");
				categoryRepository.save(cat4);

				Category cat5 = new Category();
				cat5.setName("Mexican");
				categoryRepository.save(cat5);
			}

			private void loadUom(){
				UnitOfMeasure uom1 = new UnitOfMeasure();
				uom1.setName("Cup");
				uom1.setUnit("Cup");
				unitOfMeasureRepository.save(uom1);

				UnitOfMeasure uom2 = new UnitOfMeasure();
				uom2.setName("Dash");
				uom2.setUnit("Dash");
				unitOfMeasureRepository.save(uom2);

				UnitOfMeasure uom3 = new UnitOfMeasure();
				uom3.setName("Drop");
				uom3.setUnit("Drop");
				unitOfMeasureRepository.save(uom3);

				UnitOfMeasure uom4 = new UnitOfMeasure();
				uom4.setName("Gram");
				uom4.setUnit("g");
				unitOfMeasureRepository.save(uom4);

				UnitOfMeasure uom5 = new UnitOfMeasure();
				uom5.setName("Kilogram");
				uom5.setUnit("kg");
				unitOfMeasureRepository.save(uom5);

				UnitOfMeasure uom6 = new UnitOfMeasure();
				uom6.setName("Milliliter");
				uom6.setUnit("ml");
				unitOfMeasureRepository.save(uom6);

				UnitOfMeasure uom7 = new UnitOfMeasure();
				uom7.setName("Liter");
				uom7.setUnit("l");
				unitOfMeasureRepository.save(uom7);

				UnitOfMeasure uom8 = new UnitOfMeasure();
				uom8.setName("Ounce");
				uom8.setUnit("oz");
				unitOfMeasureRepository.save(uom8);

				UnitOfMeasure uom9 = new UnitOfMeasure();
				uom9.setName("Pinch");
				uom9.setUnit("Pinch");
				unitOfMeasureRepository.save(uom9);

				UnitOfMeasure uom10 = new UnitOfMeasure();
				uom10.setName("Tablespoon");
				uom10.setUnit("Tablespoon");
				unitOfMeasureRepository.save(uom10);

				UnitOfMeasure uom11 = new UnitOfMeasure();
				uom11.setName("Teaspoon");
				uom11.setUnit("Teaspoon");
				unitOfMeasureRepository.save(uom11);
			}

			private List<Recipe> getRecipes() {
				...

				return recipes;
			}

			...
		}

	* Robo 3T, formerly Robomongo (Popular MongoDB client)

		https://robomongo.org/

	* Thanks to the NoSQL database we have less leakage of the underlying framework (JPA) into the source code. We no longer have all these annotations, relationship setups and bidirectional code going on. It results in much cleaner POJO like code.