Correcting Application Defects Under MongoDB --------------------------------------------
	1. When saving updates to a recipe and going back to the recipe detail page, the ingredients and categories are not being displayed.

		CAUSE: Under JPA we are doing a merge and don't have the complete data there.
		SOLUTION: Pass in the ingredients and category ids via hidden form parameters in the recipe form.

		But when doing that you need to refactor the categories and ingredients relationships in Recipe from Set to List type. Otherwise the array and index numbers mentioned in the Thymeleaf template are not supported.

		ERROR

			There was an unexpected error (type=Internal Server Error, status=500).
			id can not be null
			java.lang.IllegalArgumentException: id can not be null
				at com.mongodb.assertions.Assertions.notNull(Assertions.java:39)
				at com.mongodb.DBRef.<init>(DBRef.java:59)
				at com.mongodb.DBRef.<init>(DBRef.java:47)
				at org.springframework.data.mongodb.core.convert.DbRefResolver.createDbRef(DbRefResolver.java:70)
				at org.springframework.data.mongodb.core.convert.MappingMongoConverter.createDBRef(MappingMongoConverter.java:1063)
				at org.springframework.data.mongodb.core.convert.MappingMongoConverter.writePropertyInternal(MappingMongoConverter.java:669)
				...
				at guru.springframework.spring5recipeapp.service.RecipeRepositoryServiceImpl.save(RecipeRepositoryServiceImpl.java:49)

			@Service
			@Slf4j
			public class RecipeRepositoryServiceImpl implements RecipeService {

				...

				@Override
				public RecipeDTO save(RecipeDTO recipeDTO) {
					Recipe recipe = recipeMapper.toEntity(recipeDTO);		-> All ingredients in the recipe object have empty ids??? and notes has an id of null???

					Recipe savedRecipe = recipeRepository.save(recipe);

					return recipeMapper.toDTO(savedRecipe);
				}

				...
			}

		Apparently no IDs are being generated? So changed Ingredient code to

			@Getter
			@Setter
			public class Ingredient {

				@Id
				private String id = UUID.randomUUID().toString();
				private BigDecimal amount;
				private String name;

				@DBRef
				private UnitOfMeasure unitOfMeasure;
				//private Recipe recipe;                // Commented out this bidirectional reference